steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/imageloadtesting/nginx-reverse-proxy', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/imageloadtesting/nginx-reverse-proxy']
